name: "Set Environment"
description: "Menentukan environment dan optional multi deploy matrix"

inputs:
  token:
    description: "GitHub token untuk API"
    required: false
  allowed_branches:
    description: "List of allowed branches (comma separated)"
    required: false
    default: "development,staging-qa"
  deploy_to:
    description: "List of deploy targets (JSON array)"
    required: false 
    default: '[]'   
runs:
  using: "node20"
  main: "dist/index.js"
