
FROM node:20-alpine AS build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --immutable
COPY . .
COPY .env .env
RUN yarn build


FROM nginx:alpine
RUN addgroup -S www-data && adduser -S www-data -G www-data
RUN sed -i 's/listen\s\+80;/listen 8080;/g' /etc/nginx/conf.d/default.conf \
 && sed -i '/index.html/a try_files $uri $uri/ /index.html;' /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
RUN chown -R www-data:www-data /usr/share/nginx/html
USER www-data
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
