
FROM node:20-alpine AS build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --immutable
COPY . .
COPY .env .env
RUN yarn build


FROM nginx:alpine

RUN sed '/index.html/a try_files $uri $uri/ /index.html;' -i /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

COPY --from=build /app/build .

USER www-data

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
