# ---------- STAGE 1: BUILD ----------
FROM registry.pgn.co.id/base/node:lts-slim AS build
WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install --immutable

# Copy source code
COPY . .

# Terima secret multiline dari build arg
ARG REACT_APP_SECRET_PUBLIC_KEY

# Simpan secret ke file multiline & export ke .env.local
RUN echo "$REACT_APP_SECRET_PUBLIC_KEY" > /tmp/public_key.pem && \
    echo "REACT_APP_SECRET_PUBLIC_KEY=\"$(cat /tmp/public_key.pem)\"" > .env.local && \
    echo "✅ Injected multiline REACT_APP_SECRET_PUBLIC_KEY into .env.local"

# Copy file .env (berisi variabel React lain)
COPY .env .env

# Build React
RUN yarn build


# ---------- STAGE 2: SERVE ----------
FROM registry.pgn.co.id/base/nginx:alpine
WORKDIR /usr/share/nginx/html

# Copy hasil build ke nginx
COPY --from=build /app/build .

# Tambahkan rule agar route React jalan
RUN sed -i '/index.html/a try_files $uri $uri/ /index.html;' /etc/nginx/conf.d/default.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
