name: "My JS Action"
description: "Contoh JavaScript Action"
inputs:
  name:
    description: "Nama yang akan disapa"
    required: true
outputs:
  greeting:
    description: "Pesan sapaan"
runs:
  using: "node20"
  main: "js/dist/index.js"
