name: "SSH Deploy"
description: "Pull latest code and download model from GitLab via SSH"

inputs:
  host:
    description: "Target server hostname or IP"
    required: true
  user:
    description: "SSH username"
    required: true
  git_branch:
    description: "Git branch to pull"
    required: true
  folder:
    description: "Target Folder"
    required: true
  pac:
    description: "PAC"
    required: true
  VAULT_HOST_URL:
    description: "VAULT_HOST_URL"
    required: true
  VAULT_PASSWORD:
    description: "VAULT_PASSWORD"
    required: true
  VAULT_USERNAME:
    description: "VAULT_USERNAME"
    required: true
  env:
    description: "env"
    required: true



runs:
  using: "composite"
  steps:
    - name: Import All Secrets from Vault
      id: import-secrets
      uses: hashicorp/vault-action@v3.4.0
      with:
        url: ${{ inputs.VAULT_HOST_URL }}
        method: userpass
        username: ${{ inputs.VAULT_USERNAME }}
        password: ${{ inputs.VAULT_PASSWORD }}
        exportEnv: true
        secrets: |
          neuron/data/${{ inputs.env }}/ocr/secret SSH_PASSPHRASE | SSH_PASSPHRASE ;
          
    - name: Start SSH Agent and Add Key
      env:
        PAC: ${{ inputs.pac }}}
      shell: bash
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa <<< "${{ env.SSH_PASSPHRASE }}"
        ssh-keyscan -H ${{ inputs.host }} >> ~/.ssh/known_hosts
        nslookup git.neuron.id

        ssh -o StrictHostKeyChecking=yes ${{ inputs.user }}@${{ inputs.host }} << EOF
          cd ${{ inputs.folder }}
          git fetch origin
          git checkout ${{ inputs.git_branch }} || git checkout -b ${{ inputs.git_branch }} origin/${{ inputs.git_branch }}
          git pull origin ${{ inputs.git_branch }}
          curl -k \
            --header "PRIVATE-TOKEN: ${{ inputs.pac }}" \
            "https://git.neuron.id/api/v4/projects/844/repository/files/best.pt/raw?ref=main" \
            --output ./weights/best.pt
        EOF
