name: Prepare variable
description: "Prepare application version and environment based on branch or tag"

outputs:
  APP_VERSION:
    description: "The application version"
    value: ${{ steps.set_environment.outputs.APP_VERSION }}
  ENV_SERVER: 
    description: "The deployment environment"
    value: ${{ steps.set_environment.outputs.ENV_SERVER }}

runs:
  using: composite
  steps:
    - name: Set version and environment
      id: set_environment
      shell: bash
      run: |
        if [[ "${{ github.ref }}" == *"refs/heads/development"* ]]; then
          echo "ENV_SERVER=development" >> $GITHUB_OUTPUT
          echo "APP_VERSION=$(date +%Y.%m.%d)-${env_server}_${{ github.sha }}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == *"refs/heads/staging"* ]]; then
          echo "ENV_SERVER=staging" >> $GITHUB_OUTPUT
          echo "APP_VERSION=$(date +%Y.%m.%d)-${env_server}_${{ github.sha }}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == *"refs/tags/v*"* ]]; then
          echo "ENV_SERVER=production" >> $GITHUB_OUTPUT
          echo "APP_VERSION=$(date +%Y.%m.%d)-${env_server}_${{ github.ref_name }}" >> $GITHUB_OUTPUT
        fi
    - name: Variable validation
      id: validate_variables
      shell: bash
      run: |
        echo "App Version: ${{ steps.set_environment.outputs.APP_VERSION }}"
        echo "Environment Server: ${{ steps.set_environment.outputs.ENV_SERVER }}"