name: Prepare variable
description: "Prepare application version and environment based on branch or tag"

outputs:
  APP_VERSION:
    description: "The application version"
    value: ${{ steps.set_environment.outputs.APP_VERSION }}
  ENV_SERVER: 
    description: "The deployment environment"
    value: ${{ steps.set_environment.outputs.ENV_SERVER }}
  RUNNER_GROUP: 
    description: "Runner environment"
    value: ${{ steps.set_environment.outputs.RUNNER_GROUP }}
  REPO_OWNER:
    description: "Repository Owner"
    value: ${{ steps.set_environment.outputs.REPO_OWNER }}
  REPO_NAME:
    description: "Repository Name"
    value: ${{ steps.set_environment.outputs.REPO_NAME }}

runs:
  using: composite
  steps:
    - name: Set version and environment
      id: set_environment
      shell: bash
      run: |
        REPO_OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_OUTPUT
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_OUTPUT
        
        if [[ "${{ github.ref }}" == *"refs/heads/development"* ]]; then
          echo "ENV_SERVER=development" >> $GITHUB_OUTPUT
          echo "RUNNER_GROUP=Development" >> $GITHUB_OUTPUT
          echo "APP_VERSION=$(date +%Y.%m.%d)-${env_server}_${{ github.sha }}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == *"refs/heads/staging"* ]]; then
          echo "ENV_SERVER=staging" >> $GITHUB_OUTPUT
          echo "RUNNER_GROUP=Staging" >> $GITHUB_OUTPUT
          echo "APP_VERSION=$(date +%Y.%m.%d)-${env_server}_${{ github.sha }}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == *"refs/tags/v*"* ]]; then
          echo "ENV_SERVER=production" >> $GITHUB_OUTPUT
          echo "RUNNER_GROUP=Production" >> $GITHUB_OUTPUT
          echo "APP_VERSION=$(date +%Y.%m.%d)-${env_server}_${{ github.ref_name }}" >> $GITHUB_OUTPUT
        fi
    - name: Variable validation
      id: validate_variables
      shell: bash
      run: |
        echo "Repository Owner: ${{ steps.set_environment.outputs.REPO_OWNER }}"
        echo "Repository Name: ${{ steps.set_environment.outputs.REPO_NAME }}"
        echo "App Version: ${{ steps.set_environment.outputs.APP_VERSION }}"
        echo "Environment Server: ${{ steps.set_environment.outputs.ENV_SERVER }}"