name: "Build Maven Application"
description: "Composite action for building a Maven project"

inputs:
  GITHUB_TOKEN:
    description: "GitHub Token for authentication"
    required: true
  REPO_OWNER:
    description: "Repository Owner"
    required: true
  REPO_NAME:
    description: "Repository Name"
    required: true
  PACKAGE_NAME:
    description: "Maven Package Name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Check the latest package version
      shell: bash
      id: check_version
      run: |
        chmod +x ${{ github.action_path }}/scripts/check-version.sh
        ${{ github.action_path }}/scripts/check-version.sh
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REPO_OWNER: ${{ inputs.REPO_OWNER }}
        REPO_NAME: ${{ inputs.REPO_NAME }}
        PACKAGE_NAME: ${{ inputs.PACKAGE_NAME }}
        DEBUG: ${{ inputs.DEBUG }}
      
    - name: Build Maven Application
      shell: bash
      run: mvn clean package -s ci_settings.xml
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Publish Maven Application
      shell: bash
      run: mvn clean deploy -s ci_settings.xml
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
