FROM registry.pgn.co.id/base/node:lts-slim AS build
ARG REACT_APP_SECRET_PUBLIC_KEY
ARG REACT_APP_HOST_API_KEY=https://api-dev-minimal-v4.vercel.app
ENV REACT_APP_SECRET_PUBLIC_KEY=$REACT_APP_SECRET_PUBLIC_KEY
ENV REACT_APP_HOST_API_KEY=$REACT_APP_HOST_API_KEY
ENV CI=false
ENV GENERATE_SOURCEMAP=false
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --immutable
COPY .env .env

RUN if echo "$REACT_APP_SECRET_PUBLIC_KEY" | grep -Eq '^[A-Za-z0-9+/=]+$'; then \
      echo "🔐 Decoding REACT_APP_SECRET_PUBLIC_KEY..."; \
      export REACT_APP_SECRET_PUBLIC_KEY=$(echo "$REACT_APP_SECRET_PUBLIC_KEY" | base64 -d); \
    else \
      echo "⚠️ REACT_APP_SECRET_PUBLIC_KEY tidak dalam format base64, gunakan apa adanya."; \
    fi && \
    echo "REACT_APP_SECRET_PUBLIC_KEY=$REACT_APP_SECRET_PUBLIC_KEY" >> .env && \
    cat .env

COPY . .
RUN yarn build


FROM registry.pgn.co.id/base/nginx:alpine
RUN sed -i '/index.html/a try_files $uri $uri/ /index.html;' /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
COPY --from=build /app/build ./
COPY --from=build /app/.env ./.env
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
