FROM registry.pgn.co.id/base/nginx:alpine
RUN sed -i '/index.html/a try_files $uri $uri/ /index.html;' /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
COPY build/ ./
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
