
FROM registry.pgn.co.id/base/php82:v0.0.1 AS composer-builder
WORKDIR /app
COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader --no-interaction --no-progress

FROM registry.pgn.co.id/base/php82:v0.0.1

WORKDIR /data/data

RUN sed -ri -e 's!/var/www/html!/data/data/public!g' /etc/apache2/sites-available/*.conf && \
    sed -ri -e 's!/var/www/!/data/data/public!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf && \
    sed -s -i -e "s/80/8080/" /etc/apache2/ports.conf /etc/apache2/sites-available/*.conf && \
    a2enmod rewrite headers && \
    sed -i -e '$aRedirectMatch 403 ^(.*/)?\.env+' /etc/apache2/conf-enabled/security.conf

RUN echo "elastic_apm.enabled = \"\$APM_ACTIVE\"" >> /opt/elastic/apm-agent-php/etc/elastic-apm-custom.ini && \
    echo "elastic_apm.api_key = \"\$APM_SECRETTOKEN\"" >> /opt/elastic/apm-agent-php/etc/elastic-apm-custom.ini && \
    echo "elastic_apm.environment = \"\$APM_ENVIRONMENT\"" >> /opt/elastic/apm-agent-php/etc/elastic-apm-custom.ini && \
    echo "elastic_apm.server_url = \"\$APM_SERVERURL\"" >> /opt/elastic/apm-agent-php/etc/elastic-apm-custom.ini && \
    echo "elastic_apm.service_name = \"\$APM_APPNAME\"" >> /opt/elastic/apm-agent-php/etc/elastic-apm-custom.ini
COPY . ./
COPY --from=composer-builder /app/vendor ./vendor
RUN chown -R www-data:www-data ./storage ./bootstrap/cache
EXPOSE 8080
CMD ["apache2-foreground"]
