# k8s service manifest
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend-services
    app.kubernetes.io/managed-by: Helm
  name: doorv3-fe-services
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: frontend-services
