# Default values for technoday.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: nginx
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1024K
  hosts:
    - host: dev-new-relyon.pgn.co.id
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-secret
      hosts:
        - dev-new-relyon.pgn.co.id

image:
  repository: registry.pgn.co.id/neuron/pgnmobile-frontendservice
  secret: new-pull-secret
  pullPolicy: IfNotPresent

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 250Mi
