# Default values for technoday.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: ClusterIP
  port: 8080

ingress-fe:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: relyon-uam.pgn.co.id
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-secret
      hosts:
        - relyon-uam.pgn.co.id

ingress-be:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: relyon-uam-api.pgn.co.id
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-secret
      hosts:
        - relyon-uam-api.pgn.co.id

image:
  repository: registry.pgn.co.id/neuron/pgnmobile-userandaccessservice
  secret: new-pull-secret
  pullPolicy: IfNotPresent

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 15
  maxReplicas: 30
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 500Mi

secretref:
  name: uam-secret

env:
  NAF_ENVIRONMENT: "production"

serviceAccount:
  name: relyon-vault

vault:
  enabled: true
  annotations:
    vault.hashicorp.com/auth-path: 'auth/kubernetes'
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'relyon-production'
    vault.hashicorp.com/agent-inject-secret-.env: 'relyon/data/uam/secret'
    vault.hashicorp.com/secret-volume-path: '/vault/secret'
    vault.hashicorp.com/template-static-secret-render-interval: '5'
    vault.hashicorp.com/agent-share-process-namespace: 'true'
    vault.hashicorp.com/agent-image: 'registry.pgn.co.id/base/vault-inject-custom:v1.2'
    vault.hashicorp.com/agent-inject-command-.env: "sh /opt/restart_deployment.sh"
    vault.hashicorp.com/agent-inject-template-.env: |
            {{- with secret "relyon/data/uam/secret" }}{{ range $k, $v := .Data.data -}}
            {{- $k }}={{ $v }}
            {{ end }}{{ end -}}

commandfe:
  execute:
    command: ["sh", "-c", "cat /vault/secret/.env > /usr/share/nginx/html/.env && nginx -g 'daemon off;' "]

commandbe:
  execute:
    command: ["bash", "-c", "cat /vault/secret/.env > /app/.env && apache2-foreground"]