name: "Build Maven Application"
on:
  workflow_call:
    inputs:
      java-version:
        description: "Java version to use for Maven build"
        required: false
        default: "11"
        type: string
      settings-file:
        description: "Maven settings file"
        required: false
        default: "ci_settings.xml"
        type: string

jobs:
  build-maven:
    container:
      image: maven:3.9.6-eclipse-temurin-17
    runs-on:
      group: Development
      labels: [self-hosted, Linux, X64, Development]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Maven App
        run: mvn clean package -s ${{ inputs.settings-file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Build Artifacts to Registry
        id: publish
        run: mvn clean deploy -s ${{ inputs.settings-file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
