name: Data Services Pipelines
on:
  workflow_call:

jobs:
  define-environment:
    if: |
      (github.event_name == 'pull_request' &&
        (github.event.pull_request.merged == true ||
        github.event.pull_request.state == 'open' ||
        github.event.action == 'synchronize')) ||
      (github.event_name == 'workflow_dispatch')
    runs-on:
      group: Development
      labels: [self-hosted, Linux, X64, Development]
    outputs:
      branch_env: ${{ steps.branch.outputs.environment }}
      runner_group: ${{ steps.branch.outputs.runner_group }}
      repo_name: ${{ steps.branch.outputs.repo_name }}
      repo_owner: ${{ steps.branch.outputs.repo_owner }}
      app_version: ${{ steps.branch.outputs.app_version }}
      deploy_targets: ${{ steps.branch.outputs.deploy_targets }}
    steps:
      - name: Define Env
        id: branch
        uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/neuron-actions/set-enviroment@migrasi
        with:
          deploy_to: 'RELYON'
          allowed_branches: "253-devops---move-jenkins-to-github-actions"

  code-quality:
    needs: [define-environment]
    if: needs.define-environment.result == 'success'
    uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/.github/workflows/code-quality.yml@migrasi
    with:
      grouprunner: ${{ needs.define-environment.outputs.runner_group }}
      SONAR_EXCLUSIONS: "**/*.html,**/*.phtml,**/*.css,**/*.js"
      SONAR_SOURCES: "./app/Models"
      SONAR_HOST_URL: "http://10.129.2.232:9000"
      SONAR_USER_HOME: ${{ github.workspace }}
      continue-on-error: true
      repo_name: ${{ needs.define-environment.outputs.repo_name }}
      repository_owner: ${{ needs.define-environment.outputs.repo_owner }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    needs: define-environment
    if: needs.define-environment.result == 'success'
    uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/.github/workflows/build-template.yml@migrasi
    with:
      repo_name: ${{ needs.define-environment.outputs.repo_name }}
      branch_env: ${{ needs.define-environment.outputs.branch_env }}
      deploy_targets: ${{ needs.define-environment.outputs.deploy_targets }}
      runner_group: ${{ needs.define-environment.outputs.runner_group }}
      app_version: ${{ needs.define-environment.outputs.app_version }}
    secrets: inherit

  deploy:
    needs: [define-environment, build]
    if: needs.define-environment.result == 'success'
    uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/.github/workflows/deploy-template.yml@main
    with:
      repo_name: ${{ needs.define-environment.outputs.repo_name }}
      branch_env: ${{ needs.define-environment.outputs.branch_env }}
      deploy_targets: ${{ needs.define-environment.outputs.deploy_targets }}
      runner_group: ${{ needs.define-environment.outputs.runner_group }}
      app_version: ${{ needs.define-environment.outputs.app_version }}
    secrets: inherit

  # Deploy:
  #   needs: [define-environment, Build]
  #   if: needs.define-environment.result == 'success' && github.event.pull_request.merged || github.event_name != 'pull_request'
  #   runs-on:
  #     group: ${{ needs.define-environment.outputs.runner_group }}
  #     labels: [self-hosted, Linux, X64, "${{ needs.define-environment.outputs.runner_group }}"]
  #   strategy:
  #     matrix:
  #       deploy-to: ${{ fromJSON(needs.define-environment.outputs.deploy_targets) }}
  #   steps:
  #   - name: Checkout DevOps repository
  #     uses: actions/checkout@v5.0.0
  #     with:
  #       repository: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService
  #       token: ${{ secrets.TOKEN }}
  #       path: devops-repo
  #       ref: migrasi

  #   - name: Import All Secrets from Vault
  #     id: import-secrets
  #     uses: hashicorp/vault-action@v3.4.0
  #     with:
  #       url: ${{ secrets.VAULT_HOST_URL }}
  #       method: userpass
  #       username: ${{ secrets.VAULT_USERNAME }}
  #       password: ${{ secrets.VAULT_PASSWORD }}
  #       exportEnv: true
  #       secrets: |
  #         neuron/data/${{ matrix.deploy-to }}-${{ needs.define-environment.outputs.branch_env }}/github-action/${{ needs.define-environment.outputs.repo_name }}/secret * ;

  #   - name: Set up Kubernetes context
  #     uses: azure/k8s-set-context@v4.0.1 
  #     with:
  #       kubeconfig: ${{ env.KUBECONFIG }} 

  #   - name: Deploy Helm Chart
  #     run: |
  #       cd devops-repo/collection/${{ needs.define-environment.outputs.repo_name }}/helm && \
  #       /bin/bash deploy.sh \
  #         ${{ needs.define-environment.outputs.app_version }}-${{ matrix.deploy-to }} \
  #         ${{ needs.define-environment.outputs.branch_env }} \
  #         ${{ env.NAMESPACE_KUBERNETES }} \
  #         ${{ matrix.deploy-to }}


