name: Data Services Pipelines

on:
  workflow_call:
    inputs:
      repo_owner:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      repo_id:
        required: true
        type: string
      branch_name:
        required: true
        type: string
      SONAR_EXCLUSIONS:
        type: string
        default: "**/*.html,**/*.phtml,**/*.css,**/*.js"
      SONAR_SOURCES:
        type: string
        default: "./app/Models"
      SONAR_HOST_URL:
        type: string
        default: "http://10.129.2.232:9000"
      multideploy:
        required: false
        type: boolean
        default: false
    outputs:
      environment:
        value: ${{ jobs.define-environment.outputs.branch_env }}
      runner_group:
        value: ${{ jobs.define-environment.outputs.runner_group }}
      environments_list:
        value: ${{ jobs.define-environment.outputs.environments_list }}

jobs:
  define-environment:
    runs-on:
      group: Development
      labels: [self-hosted, Linux, X64, Development]
    outputs:
      branch_env: ${{ steps.branch.outputs.environment }}
      runner_group: ${{ steps.branch.outputs.runner_group }}
      environments_list: ${{ steps.branch.outputs.environments_list }}
    steps:
      - name: Define Env
        id: branch
        uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/neuron-actions/set-enviroment@migrasi
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          multideploy: ${{ inputs.multideploy }}
          allowed_branches: "253-devops---move-jenkins-to-github-actions"

  code-quality:
    needs: [define-environment]
    uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/.github/workflows/code-quality.yml@migrasi
    with:
      env_app: ${{ needs.define-environment.outputs.branch_env }}
      grouprunner: ${{ needs.define-environment.outputs.runner_group }}
      repoid: ${{ inputs.repo_id }}
      SONAR_EXCLUSIONS: ${{ inputs.SONAR_EXCLUSIONS }}
      SONAR_SOURCES: ${{ inputs.SONAR_SOURCES }}
      SONAR_USER_HOME: ${{ github.workspace }}
      continue-on-error: true
      SONAR_HOST_URL: ${{ inputs.SONAR_HOST_URL }}
      ref_name: ${{ inputs.branch_name }}
      repository_owner: ${{ inputs.repo_owner }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: [define-environment, code-quality]
    runs-on:
      group: ${{ needs.define-environment.outputs.runner_group }}
      labels: [self-hosted, Linux, X64, "${{ needs.define-environment.outputs.runner_group }}"]
    strategy:
      matrix:
        deploy-to: ${{ fromJson(needs.define-environment.outputs.environments_list) }}
    container:
      image: registry.pgn.co.id/base/php82:v0.0.1
    steps:
    - name: Pre Build App be
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
  
    - name: Import All Secrets from Vault
      id: import-secrets
      uses: hashicorp/vault-action@v2
      with:
        url: https://vault.pgn.co.id
        method: userpass
        username: ${{ secrets.VAULT_USERNAME }}
        password: ${{ secrets.VAULT_PASSWORD }}
        exportEnv: true
        secrets: |
          neuron/data/development/data/secret * ;

    - name: Check if secret exists
      run: |
        if [ -z "$APM_APPVERSION" ]; then
          echo "❌ Secret tidak ditemukan"
          exit 1
        else
          echo "✅ Secret ditemukan dan sudah terset"
        fi

    - name: Pre Build App fe
      uses: actions/setup-node@v5
      with:
        node-version: 20
        cache: 'npm'
    - run: |
        echo "APM_APPVERSION : $APM_APPVERSION"
    - run: npm install --legacy-peer-deps
    - run: npm run build
