name: Data Services Pipelines

on:
  workflow_call:

jobs:
  define-environment:
    runs-on:
      group: Development
      labels: [self-hosted, Linux, X64, Development]
    outputs:
      branch_env: ${{ steps.branch.outputs.environment }}
      runner_group: ${{ steps.branch.outputs.runner_group }}
      environments_list: ${{ steps.branch.outputs.environments_list }}
      repo_name: ${{ steps.branch.outputs.repo_name }}
      repo_owner: ${{ steps.branch.outputs.repo_owner }}
    steps:
      - name: Define Env
        id: branch
        uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/neuron-actions/set-enviroment@migrasi
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          multideploy: true
          allowed_branches: "253-devops---move-jenkins-to-github-actions"

  code-quality:
    needs: [define-environment]
    uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/.github/workflows/code-quality.yml@migrasi
    with:
      grouprunner: ${{ needs.define-environment.outputs.runner_group }}
      SONAR_EXCLUSIONS: "**/*.html,**/*.phtml,**/*.css,**/*.js"
      SONAR_SOURCES: "./app/Models"
      SONAR_HOST_URL: "http://10.129.2.232:9000"
      SONAR_USER_HOME: ${{ github.workspace }}
      continue-on-error: true
      repo_name: ${{ needs.define-environment.outputs.repo_name }}
      repository_owner: ${{ needs.define-environment.outputs.repo_owner }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}



  deploy:
    needs: [define-environment, code-quality]
    runs-on:
      group: ${{ needs.define-environment.outputs.runner_group }}
      labels: [self-hosted, Linux, X64, "${{ needs.define-environment.outputs.runner_group }}"]
    strategy:
      matrix:
        deploy-to: ${{ fromJson(needs.define-environment.outputs.environments_list) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 0
        

    - name: Generate App Version
      id: app-version
      uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/.github/actions/generate-version@main
      with:
        deploy-to: ${{ matrix.deploy-to }}
        repo-name: ${{ github.event.repository.name }}

    - name: Print version
      run: |
       echo "Generated: ${{ steps.app-version.outputs.app-version }}"


        



  #   - name: Import All Secrets from Vault
  #     id: import-secrets
  #     uses: hashicorp/vault-action@v3.4.0
  #     with:
  #       url: ${{ secrets.VAULT_HOST_URL }}
  #       method: userpass
  #       username: ${{ secrets.VAULT_USERNAME }}
  #       password: ${{ secrets.VAULT_PASSWORD }}
  #       exportEnv: true
  #       secrets: |
  #         neuron/data/${{ matrix.deploy-to }}/github-action/data/secret * ;


  #     - name: Pre Build App be
  #     run: |
  #       composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

  #   - name: Pre Build App fe
  #     uses: actions/setup-node@v5
  #     with:
  #       node-version: 20
  #       cache: 'npm'
  #   - run: npm install --legacy-peer-deps
  #   - run: npm run build

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
    # - name: Login to Harbor
    #   uses: docker/login-action@v3
    #   with:
    #     registry: $HARBOR_HOST
    #     username: $HARBOR_USERNAME
    #     password: $HARBOR_PASSWORD
    # - name: Build and push
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: .
    #     push: true
    #     tags: $HARBOR_HOST/$HARBOR_PATH/${{ inputs.repo_name }}:$APP_VERSION
    #     cache-from: type=registry,ref=$HARBOR_HOST/$HARBOR_PATH/${{ inputs.repo_name }}:buildcache
    #     cache-to: type=registry,ref=$HARBOR_HOST/$HARBOR_PATH/${{ inputs.repo_name }}:buildcache,image-manifest=true,oci-mediatypes=true,mode=max
  

