name: Run workflows For Enrergy Application Backend

on:
  workflow_call:
    inputs:
      RUNNER_GROUP:
        required: true
        type: string
      SQ_RULES:
        required: false
        type: string
      MERGED_RULES:
        required: false
        type: string
      MANUAL_RULES:
        required: false
        type: string
      APP_VERSION:
        required: false
        type: string
      ENV_SERVER:
        required: true
        type: string
      REPO_OWNER:
        required: true
        type: string
      REPO_NAME:
        required: true
        type: string
      DOCKERFILE_NAME:
        required: false
        type: string
      ARTIFACT_NAME:
        required: false
        type: string
      ARTIFACT_PATH:
        required: false
        type: string
      FILE_VALUES:
        required: false
        type: string

jobs:
  sonarqube-scan:
    if: ${{ inputs.SQ_RULES == 'true' }}
    runs-on:
      group: ${{ inputs.RUNNER_GROUP }}
      labels: [self-hosted, Linux, X64, "${{ inputs.RUNNER_GROUP }}"]
    steps:
      - name: SonarQube Scan
        uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/.github/actions/sonar-scan@migrasi
        with:
          RUNNER_GROUP: ${{ inputs.RUNNER_GROUP }}
          SONAR_EXCLUSIONS: ""
          SONAR_SOURCES: "./src"
          SONAR_USER_HOME: ${{ github.workspace }}
          continue-on-error: true
          REPO_NAME: ${{ inputs.REPO_NAME }}
          REPO_OWNER: ${{ inputs.REPO_OWNER }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-application:
    if: ${{ inputs.MERGED_RULES == 'true' ||inputs.MANUAL_RULES == 'true' }}
    environment: ${{ inputs.ENV_SERVER }}
    runs-on:
      group: ${{ inputs.RUNNER_GROUP }}
      labels: [self-hosted, Linux, X64, "${{ inputs.RUNNER_GROUP }}"]
    steps:
      - name: Build Node Application
        uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/.github/actions/node-build@migrasi
        with:
          REPO_OWNER: ${{ inputs.REPO_OWNER }}
          REPO_NAME: ${{ inputs.REPO_NAME }}
          ENV_SERVER: ${{ inputs.ENV_SERVER }}
          NODE_VERSION: 22.11.0
          REGISTRY_URL: ${{ vars.REGISTRY_URL }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          DOCKERFILE_NAME: ${{ inputs.DOCKERFILE_NAME }}
          APP_VERSION: ${{ inputs.APP_VERSION }}
          IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      - name: Build and Push Docker Image
        uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/.github/actions/docker-build@migrasi
        if: ${{ inputs.DOCKERFILE_NAME != '' }}
        with:
          REGISTRY_URL: ${{ vars.REGISTRY_URL }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          DOCKERFILE_NAME: ${{ inputs.DOCKERFILE_NAME }}
          REPO_NAME: ${{ inputs.REPO_NAME }}
          APP_VERSION: ${{ inputs.APP_VERSION }}
          IMAGE_NAME: ${{ vars.IMAGE_NAME }}

  deploy-application:
    if: ${{ inputs.MERGED_RULES == 'true' ||inputs.MANUAL_RULES == 'true' }}
    environment: ${{ inputs.ENV_SERVER }}
    needs: build-application
    runs-on:
      group: ${{ inputs.RUNNER_GROUP }}
      labels: [self-hosted, Linux, X64, "${{ inputs.RUNNER_GROUP }}"]
    steps:
      - name: Deploy to Kubernetes
        uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/.github/actions/deploy-kubernetes@migrasi
        with:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          KUBE_NAMESPACE: ${{ vars.KUBE_NAMESPACE }}
          REGISTRY_URL: ${{ vars.REGISTRY_URL }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          HELM_CATALOG_APP: ${{ vars.HELM_CATALOG_APP }}
          HELM_NAME: ${{ vars.HELM_NAME }}
          IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          APP_VERSION: ${{ inputs.APP_VERSION }}
          CPU_LIMIT: ${{ vars.CPU_LIMIT }}
          MEMORY_LIMIT: ${{ vars.MEMORY_LIMIT }}
          CPU_REQUEST: ${{ vars.CPU_REQUEST }}
          MEMORY_REQUEST: ${{ vars.MEMORY_REQUEST }}
          VAULT_SERVICE_ACCOUNT: ${{ vars.VAULT_SERVICE_ACCOUNT }}
          VAULT_AUTH_PATH: ${{ vars.VAULT_AUTH_PATH }}
          VAULT_CONFIG_PATH: ${{ vars.VAULT_CONFIG_PATH }}
          VAULT_ROLE: ${{ vars.VAULT_ROLE }}
          IMAGE_PULL_SECRET: ${{ vars.IMAGE_PULL_SECRET }}
          FILE_VALUES: "pgn-frontend/values.yaml"
          NEURON: "true"

