name: Generate App Version

on:
  workflow_call:
    inputs:
      deploy-to:
        required: true
        type: string
      grouprunner:
        required: true
        type: string
      repo_name:
        required: true
        type: string
    outputs:
      app-version:
        description: "Generated app version"
        value: ${{ jobs.generate.outputs.app-version }}

jobs:
  generate:
    runs-on:
      group: ${{ inputs.grouprunner }}
      labels: [self-hosted, Linux, X64, "${{ inputs.grouprunner }}"]
    outputs:
      app-version: ${{ steps.app-version.outputs.value }}
    steps:
      - name: Generate App Version
        id: app-version
        run: |
          ENV_NAME=${{ inputs.deploy-to }}
          REPO_NAME=${{ inputs.repo_name }}
          BRANCH_NAME=${{ github.ref_name }}
          DATE=$(date +'%Y%m%d')
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
          APP_VERSION="${REPO_NAME}-${ENV_NAME}-${BRANCH_NAME}-${DATE}-${COMMIT_HASH}"
          echo "value=$APP_VERSION" >> $GITHUB_OUTPUT
