name: Import Vault Secrets

on:
  workflow_call:
    inputs:
      deploy-to:
        description: "Target environment (e.g. development, staging, production)"
        required: true
        type: string
    secrets:
      VAULT_HOST_URL:
        required: true
      VAULT_USERNAME:
        required: true
      VAULT_PASSWORD:
        required: true

jobs:
  import-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Import All Secrets from Vault
        id: import-secrets
        uses: hashicorp/vault-action@v3.4.0
        with:
          url: ${{ secrets.VAULT_HOST_URL }}
          method: userpass
          username: ${{ secrets.VAULT_USERNAME }}
          password: ${{ secrets.VAULT_PASSWORD }}
          exportEnv: true
          secrets: |
            neuron/data/${{ inputs.deploy-to }}/github-action/data/secret * ;
