name: OCR Services Pipelines
on:
  workflow_call:

jobs:
  define-environment:
    runs-on:
      group: OCR-Development
      labels: [self-hosted, Linux, X64, Development, OCR]
    outputs:
      branch_env: ${{ steps.branch.outputs.environment }}
      runner_group: ${{ steps.branch.outputs.runner_group }}
      repo_name: ${{ steps.branch.outputs.repo_name }}
      repo_owner: ${{ steps.branch.outputs.repo_owner }}
      app_version: ${{ steps.branch.outputs.app_version }}
      deploy_targets: ${{ steps.branch.outputs.deploy_targets }}
      currentBranch: ${{ steps.branch.outputs.currentBranch }}
    steps:
      - name: Define Env
        id: branch
        uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/neuron-actions/set-enviroment@migrasi
        with:
          allowed_branches: "7-devops---setup-github-action"  
  ssh:
    needs: [define-environment]
    runs-on:
      group: OCR-Development
      labels: [self-hosted, Linux, X64, Development, OCR]
    environment: ${{ needs.define-environment.outputs.branch_env  }}
    steps:
    - name: Determine target branch name
      id: branch
      run: |
        if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
          echo "branch=${GITHUB_BASE_REF}" >> $GITHUB_OUTPUT
        else
          echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        fi
        echo "==== ${{needs.define-environment.outputs.currentBranch}} ===="
    - name: Start SSH Agent and Add Key
      uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/neuron-actions/SSH-OCR@migrasi
      with:
        host: ${{ vars.HOST }}
        user:  ${{ vars.USER }}
        git_branch: ${{ steps.branch.outputs.branch }}

