name: OCR Services Pipelines
on:
  workflow_call:

jobs:
  define-environment:
    if: |
      (github.event_name == 'pull_request' &&
        (github.event.pull_request.merged == true ||
        github.event.pull_request.state == 'open' ||
        github.event.action == 'synchronize')) ||
      (github.event_name == 'workflow_dispatch')
    runs-on:
      group: OCR-Development
      labels: [self-hosted, Linux, X64, Development, OCR]
    outputs:
      branch_env: ${{ steps.branch.outputs.environment }}
      runner_group: ${{ steps.branch.outputs.runner_group }}
      repo_name: ${{ steps.branch.outputs.repo_name }}
      repo_owner: ${{ steps.branch.outputs.repo_owner }}
      app_version: ${{ steps.branch.outputs.app_version }}
      deploy_targets: ${{ steps.branch.outputs.deploy_targets }}
      currentBranch: ${{ steps.branch.outputs.currentBranch }}
    steps:
      - name: Define Env
        id: branch
        uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/neuron-actions/set-enviroment@migrasi
        with:
          allowed_branches: "7-devops---setup-github-action"  
  ssh:
    needs: [define-environment]
    if: (needs.define-environment.result == 'success' && github.event.pull_request.merged || github.event_name != 'pull_request')
    runs-on:
      group: "OCR-${{needs.define-environment.outputs.runner_group}}"
      labels: [self-hosted, Linux, X64, "${{needs.define-environment.outputs.runner_group}}", OCR]
    environment: ${{ needs.define-environment.outputs.branch_env  }}
    steps:
    - name: Start SSH Agent and Add Key
      uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/neuron-actions/SSH-OCR@migrasi
      with:
        host: ${{ vars.HOST }}
        user: ${{ vars.USER }}
        git_branch: ${{ needs.define-environment.outputs.currentBranch }}
        pac: ${{ secrets.PAC }}
        env: ${{ needs.define-environment.outputs.branch_env }}
        folder: ${{ vars.FOLDER }}


