name: OCR Services Pipelines
on:
  workflow_call:

jobs:
  define-environment:
    runs-on:
      group: OCR-Development
      labels: [self-hosted, Linux, X64, Development, OCR]
    outputs:
      branch_env: ${{ steps.branch.outputs.environment }}
      runner_group: ${{ steps.branch.outputs.runner_group }}
      repo_name: ${{ steps.branch.outputs.repo_name }}
      repo_owner: ${{ steps.branch.outputs.repo_owner }}
      app_version: ${{ steps.branch.outputs.app_version }}
      deploy_targets: ${{ steps.branch.outputs.deploy_targets }}
    steps:
      - name: Define Env
        id: branch
        uses: PT-Perusahaan-Gas-Negara-Tbk/DevSecOps-DataService/neuron-actions/set-enviroment@migrasi
        with:
          allowed_branches: "7-devops---setup-github-action"
  
  ssh:
    needs: [define-environment]
    runs-on:
      group: OCR-Development
      labels: [self-hosted, Linux, X64, Development, OCR]
    steps:
    - name: Download model file (best.pt)
      env:
        pac: ${{ secrets.PAC }}
      run: |
        cd /home/developers/PGNMobile-PGNOCRService
        
        curl -k \
          --header "PRIVATE-TOKEN: $pac" \
          "https://git.neuron.id/api/v4/projects/844/repository/files/best.pt/raw?ref=main" \
          --output ./weights/best.pt

    - name: Start SSH Agent and Add Key
      env:
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSWORD }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa <<< "${SSH_PASSPHRASE}"
        ssh-keyscan -H 10.129.2.35 >> ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=yes developers@10.129.2.35 << 'EOF'
          cd /home/developers/PGNMobile-PGNOCRService
          git pull origin 2-devops-setup-cicd
        EOF
